function getRandomInt(max) {
    return Math.floor(Math.random() * max);
}

function roachBehindImage(roach, image) {
    if (!image.complete || image.naturalHeight === 0) {
        // the image hasn't loaded yet
        return false;
    }
    const roachRect = roach.getBoundingClientRect();
    const imageRect = image.getBoundingClientRect();

    // the BoundingClientRect includes padding, roaches cannot hide in the
    // padding, so the padding needs to be subtracted in the calculation
    var imageStyle = getComputedStyle(image);

    return roachRect.top > (imageRect.top + parseFloat(imageStyle.paddingTop))
            && roachRect.bottom < (imageRect.bottom - parseFloat(imageStyle.paddingBottom))
            && roachRect.left > (imageRect.left + parseFloat(imageStyle.paddingLeft))
            && roachRect.right < (imageRect.right - parseFloat(imageStyle.paddingRight));
}

class Roach {
    constructor(name, speed) {
        this.name = name;
        this.dir = getRandomInt(24) * 15;
        this.x = getRandomInt(window.innerWidth);
        this.y = getRandomInt(window.innerHeight);
        this.speed = speed;

        this.element = document.createElement("img");
        this.element.style="position:absolute; z-index:-1000;";

        document.body.appendChild(this.element);
    }

    roachIsHidden() {
        var hidden = false;
        document.querySelectorAll('img').forEach(image => {
                if (roachBehindImage(this.element, image)) {
                    hidden = true;
                }
            }
        );
        return hidden;
    }

    moveRoach() {
        const dirModifier = getRandomInt(3) - 1;
        this.dir = (this.dir + dirModifier * 15 + 360) % 360;
        this.x = this.x + this.speed * Math.cos((this.dir * (Math.PI/180)));
        this.y = this.y - this.speed * Math.sin(this.dir * (Math.PI/180));
    }

    wrapAroundBorders() {
        const spacing = -50;
        if (this.x < 0) {
            this.x = window.innerWidth + spacing;
        }
        if (this.x > window.innerWidth + spacing) {
            this.x = 0;
        }
        if (this.y < 0) {
            this.y = window.innerHeight + spacing;
        }
        if (this.y > window.innerHeight + spacing) {
            this.y = 0;
        }
    }

    move() {
        if (this.roachIsHidden()) {
            return;
        }

        this.moveRoach();
        this.wrapAroundBorders();
    }

    redraw() {
        this.element.style.left = this.x + 'px';
        this.element.style.top = window.pageYOffset + this.y + 'px';
        this.element.src=this.getImg();
    }

    getImg() {
        return eval('roach' + this.dir.toString().padStart(3, '0'));
    }
}

function roachesAreGo(roachCount, speed = 20) {
    this.roaches = new Set();
    for (var i = 0; i < roachCount; i++) {
        this.roaches.add(new Roach("roach #" + i, speed));
    }
    const interval = setInterval(function() {
        this.roaches.forEach((roach) => {
            roach.move();
            roach.redraw();
        });
    }, 50);
}

const roach000 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAJAV1vSS+AAAA/ElEQVRYw+1WSQ4DIQxrRvz/y/RQIchiMBSkqiK3IcHOzkh+nZXnMP4l
uAR/TCD0fD5rF7MsRzCmkIxtvMadSO77h/WxJnCmPbIXNIi9HBF3M1KULSSCR1ETVa1et/6PUjlB
gMy4TkqrzFl8AiMJBk1yrxERqL1RvtU5P5/Vf0/XNkKDyYN/ANmqbFl2vSokxmgkvegTZ8Z7bOX4
e5C+h9Ax6R5ajCBacnrsqsWjzXbEYCMa+ofguFUxREMGbLz0Ni259Yt7iSB+q+x7wERD1MCurrkn
E8wB8glvUZTr6b8KP0p9jSHgiocpiAjYa5vbdF1+9e/6ElyCSzAjb6GSf0lEC3N5AAAAJXRFWHRk
YXRlOmNyZWF0ZQAyMDIyLTA3LTExVDIyOjM2OjA1KzAyOjAwrMP+ZwAAACV0RVh0ZGF0ZTptb2Rp
ZnkAMjAyMi0wNy0xMVQyMjozNjowNSswMjowMN2eRtsAAAAASUVORK5CYII=`;
const roach015 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAJCQ51DTgAAABIElEQVRYw+1WyxKDMAgMnfz/L9NTGjDLy8ZpD8lJR9xdFgSJ27Pn9TD+
ITgE/0NA5udUJMBA5HytGzIgbo3Jetq/0U+JOVMimEoltK2+SDBBx5UPXSS4Op0Bb00UOfZT2pOF
FxkwzRexw8TjmmnEjHibUAnXWaww65MhzDYt0WlryASVd5jALXKmz2U0ouhWsA10hfFlAIJIt1dS
jcAECGq24KzknSLwwX3dVl5dhvjAqHNi+g8BasasaV5u3Q6PDMtVC0TlXrx+5ymCWgflBp7AvNOg
3nC8kcGwBVcJT9bUwll12ibVBokK07rLG80Dx1bkCII4b5nEQy8g0BsMR8QUJkFttdvHqcEO+N/9
vt9bO6UM9hi0U2o1g0NwCNLnDdMVh2X/8bdyAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA3LTEx
VDIyOjM2OjM2KzAyOjAwE6TjGQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wNy0xMVQyMjozNjoz
NiswMjowMGL5W6UAAAAASUVORK5CYII=`;
const roach030 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAJCw3D7zSAAABJklEQVRYw+1WSRLDIAzDHf7/ZXogDIs3ASVtZ8Ix2JIlGwilcHa9DuM/
BP9PQO4QbhH48DdYFPeqT3RIgQwvWYbYeAUWuJLiVz9hUa0DtWbRIkohJGrhM6FuBESQYeW9RK19
yxb1gNWojx20vsICyxu/rEADoNSr4GZBCqyZqWrkyOin+vRuk/uA/iCNNBysDKpMcuWPMFbz8mCi
FsYxSdLiLcsiFUPeqECoBoVAs6bVWWOQKYNqb3ckU6V7lqFhbZXqht4IGQY/Efxb9BN0+HpNgE3m
k6GB4w9O1AEsY6zJdwls8LJrPUKqReonZs44sBMKbNflSQfuIr9m3ZRJBVoi6jnqiBC0Ag89mTvw
QA9WrZlQsLcAgp36b1AA/77/rIKH4PsEbwQ/mGVcx45HAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIy
LTA3LTExVDIyOjM2OjQ0KzAyOjAwjv77KQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wNy0xMVQy
MjozNjo0NCswMjowMP+jQ5UAAAAASUVORK5CYII=`;
const roach045 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAJDAjDuCdAAABKElEQVRYw+2WSRICIQxFicX9rxwXFEWAzIj2wiyx+/3+mQSw3I3XZf5f
4JIABDrjmQ6+IOBPUs2hES45iOJTKZrxVrJCAoAUD1gKoOXGIdC/ccaXgtAkhgfOTbjIUlIAETg3
pgOKQ+Dxq7dgis4iXGQuWjUOBWQEgjYZpkDL+8BHhszpgCK5cuqjpgq0V2eA1jHtd+pXmQMOTl15
21UQGI+uoA7YZ0IaQOFIxvczbuntydsEvHgubdxpldPgwfdayGUnb6zWZxiPL2ZU6XEb7wuli/SE
eWeaFbBX9H4qyYltauG9oa6KfOYVgXlvnn296kDCRx0JXZTteoeD/v/km+6UA6sFY04c9yK6OuJp
UmrwmQjdKjKyz7l4ZZP2HAfZON1lv3dwXeANNkORbQYDg/kAAAAldEVYdGRhdGU6Y3JlYXRlADIw
MjItMDctMTFUMjI6MzY6NDgrMDI6MDBJXpFdAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA3LTEx
VDIyOjM2OjQ4KzAyOjAwOAMp4QAAAABJRU5ErkJggg==`;
const roach060 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABOklEQVRYw+VWyw7DIAxrpv7/L2eHiqWEPBwK0qRymtphxzYJJT72rs9m
/LcTEBBgiUADMm1WgKxXE/SJeIEXCKKIib3AYQJigSQ+DmLiRunDT1rEJNBayyTBvf7erKzZTrxq
Gy5rtlCBhrOrjTUkFslmG4Yp0/Cw0UaN+klIILVdv6xa7xr7o1BS0GCySMf3ySnrX0cnyaoeUNBv
sdsqggcs0hQXlE7HX3CjCaA9RT2iMAPkzn3QBxb86P/0qCAeN2t7kOVkUDXHH9thyLoLxsEgzzyr
Tg84t4fJHg4pQdsU25TPUYPAlzsTr0GAVCTFYP8OjumK+qFxbRm2lMAe2g8JBFLb0+BRmtJ94F85
ZQL7Iwu/BUAFNkztRLmzaDSjFi6k4B7pHHxV72/TogxWrO0E80PmXxRsJ/gC5MeSaTWZXywAAAAl
dEVYdGRhdGU6Y3JlYXRlADIwMjItMDctMTFUMjI6MzI6NDIrMDI6MDDkxW5pAAAAJXRFWHRkYXRl
Om1vZGlmeQAyMDIyLTA3LTExVDIyOjMyOjQyKzAyOjAwlZjW1QAAAABJRU5ErkJggg==`;
const roach075 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABKUlEQVRYw+WXyQ7DMAhES5X//2V6iCJTbJaBWEpVn7qoPM9gxinxa+96
b65fARAkersCbDuF9fsWJQA9F1MKvhFMCDwBkAV1Uf1dUYEujph2oAbJz+L9wwqY0JbDx3Tseu7N
Cp6wSBsz3mnEyjIA4JlDbHUkZRGT12p/GYD7MtAAMMmW2bgxF9aRNS3SpyVz5iGA3Pmph6kCcc0e
B1FPrnzvGRQCPOuGPk+BOwfrYLDDGwbME2CVs9VAUWHt38vWcJLjkfOj+4h/Wi+eskg2ei4UT4YD
OKdARzRW/hnPRZ7GBiC+r3LJBCmo3BLlCyebrEuAn49tBbK8NQN5/GIOokBrK4iXjLgmoN+JpAIJ
ul7fPAfr6zObtwBgfuRt3MmWSch64v/kfwN8AMLXfGv6nSNQAAAAJXRFWHRkYXRlOmNyZWF0ZQAy
MDIyLTA3LTExVDIyOjMyOjQyKzAyOjAw5MVuaQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wNy0x
MVQyMjozMjo0MiswMjowMJWY1tUAAAAASUVORK5CYII=`;
const roach090 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABBUlEQVRYw+VWQQ7DMAgb1f7/ZXaallZgOyTZUo1bW4oxhgTzx1o7Fsf/
ZwATxVP9vs/gjgC1agKAa0C3ChT0NW/Dfpzbd5FfqURtJj0MZIAsQ/a1U+QoEObz1AHc3sEwmyJA
pIECBEvEGlMRm2owelhNOSpQqQ7+K+bAGIoMohzd3NrWNY/AkgTOPR815/Vd95Scc2vzPj/h8KBE
vPoZXxFAh0DhhUlWegi1KQSINIg9ctvhTkZF4hoNn0WTJjmzYQ3M3VgQzGFYZAa/QxflWfI5IQAz
Vu89SoQNyzyJQV5Msl1rK1b50tc3uNJu2v4UX/oK9PIu6mp18561twBQsTsM2o8BXtFCZlv84TYX
AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA3LTExVDIyOjMyOjQyKzAyOjAw5MVuaQAAACV0RVh0
ZGF0ZTptb2RpZnkAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMJWY1tUAAAAASUVORK5CYII=`;
const roach105 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABJElEQVRYw+2X2w7EIAhEpen//zL7YIxFuQy1Jk22Pm0T5DAOXpa47B3H
5vwf4AOEg8IuDwFxikUA0xp8uwcnEiQr9TRBCohH6deUufQqgElCJC5ruuqBrLJ+MTHVXx2BqDE8
YJrXfdSELZbTRVfE7MvSEo31IcmtmCOeZKcnbmXYMbc32qjQcgQAaFOr6YjN7vL2ylqY/WXBAv9k
qnlSa19bC9R916Bxh3jVl2J6gHd9299JQN1aGgazNgTM587dEXaRBs+44F44fZpXhwYMl8gXnXHh
kTvZ0wABtp2mXs1oJAiQ20nvIl3DO95FmEb92Eso0N4apcizde4nEDBOs/tqQUH+VZcG3MEmAflX
alpB/FCRA2hT+85dflU8Md7+L/MfAD8byXpfUCL43wAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0w
Ny0xMVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6
MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach120 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABTUlEQVRYw+1X2Q4CIAxzxP//5flAkAHrDpBEE3nkaNeOYxA/7rZyGf9P
8CsExH7PEQHTZQX78UMCGyKjqCCIkWI/C9CiNcqMMalVbYqkrH0Rq5wkE/cIZCzxLLgK+gSmMXLi
CJGroEIwMXU1c1RWlMWe2uClVTmjyryEeAabt+wciO3yYhFT9xo3pmiiC1qu7x4Z95j+FAEywzIt
s/490LcjUnegQAdaobQ+2Z6+yA5QVeXuJHO2PqhRYBWmgrbMj7md+LVtvGgrmHVyigWEDRh7KqVO
AQmI62HSlqF7KTo3NDimGl/giT1nX4GIYruy0/dNNUoaGzhoUZukkg0Fq3ivsEkStLfNjveAQIOM
PPuH5bv/dKYI9HLL1pAg6EBrjfcxi9AFjpUkK1r9IT169LFhsbIlfZIl7Aeq69WgbEtalP8OXv8n
7/2LvknBC16jpFcGLWfqAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA3LTExVDIyOjMyOjQyKzAy
OjAw5MVuaQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMJWY1tUA
AAAASUVORK5CYII=`;
const roach135 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABHklEQVRYw+2XSQ7DIAxFccX9r+wuoojB44dEjdSwSijx+x4wlLjcOz43
238BL0AMgqv6tx7MenH98DfEpTBd5oEcTKimEDCbQxECIA1q5vIIAZgVSlNMLQvEEapqk4fqpr1/
w1Js5qBXOXqClqqb5ANiobYBdkiI85jEumiJn5WFXtQblLly5WlBifZFBKhysddv5HxUvEaI9Ljb
ZuwNp86fk/2ubs9a8zh+tSrOIfeftKUSYQfXqUGvPD2Evy4N8xF9O0wBEMQ4Ng59mVRNbY2M2NpO
hB8EIMl6wmbEXu8tOALOgd4s4Fbh+YAhFu5F1oFqFQLsgb1rLwGMauOzYftEy8jZ8iEaS60CuZ8u
9qL8/e5p/9H+EbBUpo/y4AtpNJtJm3+65gAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wNy0xMVQy
MjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6MzI6NDIr
MDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach150 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABHklEQVRYw+2X3Q7DIAiFZdn7vzK7sMYfEA46kzYpV8tq+ThHaC1xOhuf
w/lfwAu4gjZ6GVSwjoAATMcVpES8pkIFyFRZwwpCBWiWSASGC7QpE1NchQvoE/YIBOYCRruiHfVF
qmeqv1rUpgLNingfCQXE0pSxdyIYoaCkl/bIGNfaPqiXZGMiQNOi1irMjqqjtTffBzSCNQeWWeUf
s01xT0vt0qSQAm9ToT0o3mm3t+OmQWSLi3Xzesft8nbDsUjqmCWbvTscgHPJgXiFhYHaOC4A7MU9
pALCc2DBNbsgBWNlnpI2gHeyJhxZHVCg24E9VRfPhMXxrTnwjVix7O+QnZN5ah9+s9j6AMlnPTvu
8YVjq3i6Ai+2uugWCp4P+AEECpVNXwgDtwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wNy0xMVQy
MjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6MzI6NDIr
MDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach165 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABDElEQVRYw+1Vyw7EIAhcNv3/X2YPxqjIY2i12SblaHEGhpESf/bGdzP+
S/ASPJ6AFrzCoIPrFAFC+cwkz8aTywQlGmiGAtKgJRVYrS8rDiSpQlUiJnw2YsjRxUZxksC/iMMG
EhFXraU4Wo/+hExNeqf0EPLC6C3/VK1shNTH60lnvuTMG/ZyXYlyhtQ7WbpNiedyTAJd19iokuKw
E5GBahmgTTUIptn1Nkz5Du0iHahfG7bvAZOgK06fD7yuccOGU8JVRkimexZQv8gyFKCL+opGL6U7
iOnkKvcDtun8L8Moku+gQTahfBpYIqte3XMnCOICbljXWiwjsCax+IezlWDzkK14zpBfgv8l+AHt
UYhLL87tIQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMOTFbmkA
AAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSu
QmCC`;
const roach180 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABBUlEQVRYw+2W2QrEMAhFx9L//2XnoUhWr9eUwDAkL22J8bhErehn77o2
6z+AAziALEAWyj7pAYNoZa6MIpUYIapSf9+xHe2BUQU2DBjUbhWloi3UkwsBvt3l3Y77PtFJVvFs
UfHVJ2+ej3gJKFFnxFscHSLeVdFa9kKC82fOHPqamvs85gmV68FK3xnVg0r2LEY3ZrbunDjvmRmy
bR6YIW43xfXJrw5Q9xbUNfkQESGtG3c2A1SSTW3kz3yfNOkJlwXNH0bLgAKp3/rRkwKMG7OZhqQg
wB+DOB+jTwAwUxKnuz/pFBoqMxz1fjfdKuJ701ZLcibna/tt2w/Xb/1dH8AB/CngC/q1e03scSEI
AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA3LTExVDIyOjMyOjQyKzAyOjAw5MVuaQAAACV0RVh0
ZGF0ZTptb2RpZnkAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMJWY1tUAAAAASUVORK5CYII=`;
const roach195 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABBklEQVRYw+2WyQ7DIAxEccX//zI9IGSLeJlpxSESPgb8xo6XREY7a5/D
/CtwBSgTt+PflMFhARlD/hCQkZ/G5x2PsDUvxon2o69DS0EVmsxggvY8KjyRgTqoVBZKKKCJ2yN1
wiIq7u9o+7bRlJcEWWTU2IzBqxZLZLCuDIku+7D5FG7TGZWHyKMsBazzkmAKmAj462tv4MiWb5qB
J8GUOhWgR9yBtwas62LwC3xZ5OgzgqALgbjrY7hODJCzbs1Mih2+h8i+4oZYYcbTid1zsWdYffoT
5LvtT9EK9QrkA/EpgZad4ux7xRq4nIMoMwxf7qIIheLpVcHbbzuNsPf8XV+BK/BigS/yEIdlJOsv
oQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVY
dGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach210 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABK0lEQVRYw+1W2Q7DMAgrU///l9lDhHJwGHqo09Q8rV1igw00xNu963Mz
/kvwDwQEyvD3M3icYD9zmHjbmG4jIB7BxeyVEBUBjF0DzBTQA2INEcFbe9NbJDb/kHakIBGKu4OP
7pQ8iDav2cnzqTLNSAcIxnhiYeZ/u0R7BroGPlutTnqRePWO+sAIrb1ao5hF8vM60MmrD7lSTROM
G1CjWYOvVKatgXKGy3Pxe4BiF/+YZIbtERhTttH1vMJzK4h29UXXXV+w0eLVQKOvmvJAtOuHouM4
DJWBBae9SCjsZWBT2dMlIyMo01Zw8kuo0E0ilEjnMLtRvSUEGVhQ47vMrSjMwJ6LnjPFDOyrSk19
Xwd3Wx0+OU1zapckum4lCY7Gf/jye3kGL8FLEKwvv2GVYRVSw0IAAAAldEVYdGRhdGU6Y3JlYXRl
ADIwMjItMDctMTFUMjI6MzI6NDIrMDI6MDDkxW5pAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA3
LTExVDIyOjMyOjQyKzAyOjAwlZjW1QAAAABJRU5ErkJggg==`;
const roach225 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABIUlEQVRYw+1Xyw7DIAxrpv7/L2cHNAEhDycrWqWV26pg17HDKPGxd702
49+YgMDe3lfB/xCctW3S4vab6SIC4g4WpalA0OGRqKY9sOGZjoNYPi2Y7MFfoKDrQODLHqDwAMFn
oxbBGD5o0WiZBSHh5Yugh6JauNq96oRNXrfqsZQLNhnJjVTEFBKgnZfwXa9LYJ05Vm60xJ0e+FjK
NG7XZ0GCOwQzvHwze9TWKChKPThvqPRRFNVzArSSlcKecaVFfnGji2vGVThNcxQhgT+p/kGntEgH
0f7iURWBAvu2cMnVsYG0981ZCxL0SSAm7iQzWSqmK8XcpLwOdZK1gR+f2c5ABMgWXMkXF68tBFn4
goKszb/9ACkkYAtGXcFD8BBA6w373o9t7kLJxwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0wNy0x
MVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6MzI6
NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach240 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABNklEQVRYw+1WSQ7CMAyMUf//ZXOIoiSul7HbCgnwDRFm8QpxezZeD+P/
HgGlS3bZQUSZJlgBiYkjirKDDt5aa0yekzSBhPPhb+qiDq+TpAiIdf1eFBxIpbcVuetf4Xb9upvL
gxbNwVGHl37Or5hSBEye2pGg/mamK+Ug1j/6bAZQgzGzsrxYPVwH025UyqH73EkH8jOZf1w/3Kbx
HSDWJ6EwyZp+Cx7oIr/TV1I9gCJHK83/1iGwbOfusvl6hY86yPMADdr+aZ/WaEpKF21SFA9OXw4x
SAyvFvm8sPQ3WLHBlrCejRttSwpr0P9aMUmI/bOtE3CwnpD1WtnrYQ344MhLhUaqTf00lVI0yyf3
EpagcNnJmc2HmyIbEtXvEEQLDfVjEtQSkkzRNxFkToz/y085+BM8GG+fWpFrUklZNAAAACV0RVh0
ZGF0ZTpjcmVhdGUAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9k
aWZ5ADIwMjItMDctMTFUMjI6MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach255 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABJ0lEQVRYw+WW3Q7DIAiFx7L3f2V20TQo/6AmTerNUrv6cQ6gAn7Oju/h
9d8BANTmIJm8lAK+GD3HoAQAYUbYuLaCEXH/Imy0yBqZPBQB2dQ2ADlLZNJ/vfg13PWWv1nIgWaX
BBf6wPcfUNf1hK1CtpqecH22rWA2zLYvCcj27UYFHG6FELSmVYp83lboNhqVnheHb59jUX3fKSkA
pMhWUKlveQ/Ij5o5kFrkuID2f8Iy1T6tdEVYploV0dyNsra6QAE/h2k+n/agTG0zABEQxiuADl08
cEbEwm7a3+oCAC1sxRcPow+kn7MhmT3KBcy28GKtqDEsmpfwnpoAf8Tnc8IivqTWsxvvppV7xAaL
Zm1HAbGGZQURYs/Bu1NBNaLjl9/nWfQ+wB8dln5j4akdQwAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAy
Mi0wNy0xMVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFU
MjI6MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach270 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABAklEQVRYw+2VwQ6EMAhEy8b//2X20Ji26syQtu42US4mWnkDFDBP99rn
Zv9PA5ib18/JgNZpFPHPFCnF9RucNAJwi+baPCW3jhS5RXLN3Msa7D9eYyLxrdUHLwCYLiW+Q8EI
MELDJYCpywh+IhABd6AEhFKknAwDRmxTB1QZ8/fuWWTupmrARyIFRLcWQ4iFk9WXGFA0OEpYg/OU
P2Nq1W7XHRHIQkG1h/d3vEYSgNwXCEeEO5ntNKZSXlMtgNsK+yDbdZ71lJKjonXWXsypEWDtw/sA
WewCyFmE9dVfMEzU4OgelXpkawcN9XN3DY7KUCqnRYBsnU7+AaAvm28NHgD4AsmhZl3/7c/6AAAA
JXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA3LTExVDIyOjMyOjQyKzAyOjAw5MVuaQAAACV0RVh0ZGF0
ZTptb2RpZnkAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMJWY1tUAAAAASUVORK5CYII=`;
const roach285 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABLklEQVRYw+VX2w7DIAgty/7/l9mDIaUqHFBMlpS3GXcuIGKJr7PxOYz/
LgJi4tnqNoEG7uGImYpTpCmQ+hBBAyG+LtEqsHqt0MFNgcGXCTIxEMzPSp/vSPYNAiYm4jnNmBRM
NE0RExP6c6zEyUaL7w0QYHUxQscB05iG56+SRvNju9FWD2fCAQK1+iYs6rnBOr52qqADVFbpGUtp
oMi4kN6OLyaIxEaKevN4hqUdtIaz9KLZAAh6vf1UE3rbl0sgMOJh9NKgvbMOaqB12UBeVVwCnRBU
2o0+0K+IfARvU1t/4cNrBiVr9ohNzQNPrUWRHDjtatOhO2JGEapc30ZPUD+CDuY6/BZrsXSb3rrL
HNhABR8gq9QxAdtR8nzfuE1jgMu36Wl3JfFPH+JvJfgB406CYfM8NCsAAAAldEVYdGRhdGU6Y3Jl
YXRlADIwMjItMDctMTFUMjI6MzI6NDIrMDI6MDDkxW5pAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIy
LTA3LTExVDIyOjMyOjQyKzAyOjAwlZjW1QAAAABJRU5ErkJggg==`;
const roach300 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABMElEQVRYw+1X0RLDIAgbu/7/L7MHz+tAokHtzYe5t7UlJARoRV/PnvfD
8Q8FkISuJzAQtRln8icASjgPshFAxWd+/7MIULNuITIyDRjMCkMAfIf2HDIiQYAaxHOoECw3yqY2
5802RZAbAKzyVnce4oofi8rI6w4ZqJQfKu2MWOAO0cLBmxUFxMal+qB3KmM0rWCcUlh7ueUwbrlu
o1WhcDZjnulZlJullNReFFv40RCfAEB3xBCUWSII25Rtr08yiGdsD4LYycXpo6xQG5IuKhBtd49P
elzj8LWjpwGQCLeA0aBcfrPzIX3FyPciPEWxQSkA/2jkp37RaUvgwafir6UkQrlU46r0l+k1CsvJ
t4FBZlNPStRmyeyGE75wfgqwvJPtye5jLoXFc3oN/gAbzgd/ZppTYSxRRwAAACV0RVh0ZGF0ZTpj
cmVhdGUAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIw
MjItMDctMTFUMjI6MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach315 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABJElEQVRYw+2XyQ7DIAxEQ9T//2V6QIjNY8+kQaqicGpZ/LxDUj72jnOz
fAWQLhn7Txa8gGWkfC2ss5RwIad+pv67wYLZkiJatQoCRk0LRNUeKNREzYt1VgEBC2x/V6DiJugi
H3EDwEO0vIqB5o45RddNOaEIiQA/OZlgn9FBXF5cLtGFtorjAn5awvzQaiCn0KwgImHYXTDIMWKM
lGRfcxNGjL+wE4l2jZxhVYuYCuUIanms8454eMIiG6g7uT/klVdO6+pH1d+a8aCkBVU32z2en4Vn
i61nEY8RP7+LoiyhAHGq4aZOBHnG5NQaw9gapUrut/TimA7Uz4u3uCXSf8bIQbbvZ2U/BeCfXrIF
Gx6/DGJjoVUoQtzxjeGOR3+jvYCnAL4riKdHEozNyAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0w
Ny0xMVQyMjozMjo0MiswMjowMOTFbmkAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMDctMTFUMjI6
MzI6NDIrMDI6MDCVmNbVAAAAAElFTkSuQmCC`;
const roach330 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABIklEQVRYw+2WSw7DIAxE7ar3v7KzqAgx/jCAaCsl7BKEH2OPARbaO16b
498BwItF+r2CVQ3/oGBtQPpZiIQ3KhCer4Szrv7Su57TkQJazAzije5BmEi4wiOdgILk9xmuQgdT
xKITEg80VcZFLCVwFgKvhFHQhkCSleFCAAbpqzJrI5P6ED3rIYA+0M6JE3Sd71qlB/G+/HqE6fUm
9K79HXfj1E5Asj4IaE0aI+Lzqh3nWaTLVVyxeuVDNWgxERbsg/4+Ml0WAt7JdaENUf4Ie+4HASxl
uS1vbGgi6MLRDeXbM3YRfOnb75qS7DSFFOTI/G6AH16zHTHsok8b4rjhFBUvoU+Y6bMAfVdMP36v
bbUFgI4lAHLarp/HOxU8gAfwHcABrFWcR5riwiAAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjItMDct
MTFUMjI6MzI6NDIrMDI6MDDkxW5pAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIyLTA3LTExVDIyOjMy
OjQyKzAyOjAwlZjW1QAAAABJRU5ErkJggg==`;
const roach345 = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElN
RQfmBwwAICq6ANzjAAABF0lEQVRYw+2XSxKEIAxExeL+V2YWFgUhnU9buBllS+hHJwG0tOPZcT6s
/wFeDCjbutcAtLIL4aRoD8KtwQ6EozGmWrEirBlqk1fILNUXxfJEFsZuNZACIOIldiFKy4sDvZyh
AYjd1Fv5WqLXdahetxBaSHsxFWNUrhJCB/W1BeoFj1BVSunDJZuT8wgcxGnouZaxtod6uEMngTkD
cNO+8fUE2FG9niAuyq25ELo7UVgrUSKyFXDegxiy4nD8aYXbS7jTXtFyfbdkSx9uZ76M1xaVzrBP
fReEV4VGzw2I4qUK8aLNXvwGmOfTX3YyLfmaEC0xN2P+2ad6bs16BkN+W1kvho0gv66RUFRwjkCP
v/0B+QAf4FWAH+umlEOIyDx+AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTA3LTExVDIyOjMyOjQy
KzAyOjAw5MVuaQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wNy0xMVQyMjozMjo0MiswMjowMJWY
1tUAAAAASUVORK5CYII=`;
